package com.example.ordercar.util;

public enum Step {
    TRANSPORT, DOCUMENT, GETFULLNAME, GETPHONE, CHECKSMS, PAYMENT, GETTOWHERELOCATION, GETFROMWHERELOCATION, DELETEDRIVER, SETTING, GETPHONEOFFLINE, GETFULLNAMEOFFLINE, PHONE, REGISTER, PASSWORD, NONE, ORDERCONTROLLER, MAIN

}
