package com.example.ordercar.util;

public enum Step {
    TRANSPORT, DOCUMENT, GETFULLNAME, GETPHONE, CODE, CHECKSMS, GETLOCATION, PAYMENT, GETTOWHERELOCATION, GETFROMWHERELOCATION, DELETEDRIVER, SETTING, GETPHONEOFFLINE, OFFLINEORDER, GETFULLNAMEOFFLINE, MAIN

}
