package com.example.ordercar.admin.util;

public enum AdminStep {
    COMPLETEDORDERLIST,
    LISTOFACTIVEORDER,
    PHONEORDER,
    MONEYINCOMEHISTORIY,
    ADMINADDDELETELIST,
    DRIVERADDDELETELIST,
    ADMIN,
    ADMINANDDRIVERKRUD,
    ADMINFULLNAME,
    ADDEDADMIN,
    ADMINPHONENUMBER,
    ADMINADDEDBACK,
    ADMINID,
    ADMINADDEDBACKKRUD,
    DRIVERFULLNAME,
    DRIVERPHONENUMBER,
    ADDEDDRIVER,
    DRIVERBACK,
    DRIVERBACKTOKRUD,
    DRIVERID,
    DRIVERDELETE,
    MAIN

}
