package com.example.util;

public enum Step {
    TRANSPORT,
    DOCUMENT, GETFULLNAME,
    GETPHONE,
    CHECKSMS, PAYMENT,
    GETTOWHERELOCATION,
    GETFROMWHERELOCATION,
    DELETEDRIVER,
    SETTING,
    GETPHONEOFFLINE,
    GETFULLNAMEOFFLINE,
    PHONE,
    REGISTER,
    PASSWORD,
    NONE,
    GETMONEY,
    SAVEORDERPHONE,
    GETMONEYPHONE, GETDATEPHONE,
    DELETEORDERBYID, DELETEORDERLIST,
    DELETEORDER,
    HELPCOMMAND, INSTRUCTIONCOMMAND, CONTACTCOMMAND, LOCATIONCOMMAND, CREATEDCOMMAND, SAVEOKPHONEORDER, DELETEORDERBACKMENU, METALBUYUM, METALLPROKAT, LOCATION, CONTACT, BOTINSTRUCTION, SETTINGS, TRANSPORTCONTROLLER, MAIN


}
