package com.example.util;

public enum Step {
    TRANSPORT,
    DOCUMENT, GETFULLNAME,
    GETPHONE,
    CHECKSMS, PAYMENT,
    GETTOWHERELOCATION,
    GETFROMWHERELOCATION,
    DELETEDRIVER,
    SETTING,
    GETPHONEOFFLINE,
    GETFULLNAMEOFFLINE,
    PHONE,
    REGISTER,
    PASSWORD,
    NONE,
    ORDERCONTROLLER,
    ONLINEMONEYADMIN,
    ONLINECASHMONEYADMIN,
    ONLINEMONEY,
    CASHMONEY,
    GETMONEY, SAVEORDERPHONE, GETMONEYPHONE, GETDATEPHONE, DELETEORDERBYID, DELETEORDERLIST, DELETEORDER, DELETEORDERBACKMENU, NODELETEORDER, SAVEOKPHONEORDER, MAIN

}
