package com.example.util;

public enum Step {
    TRANSPORT,
    DOCUMENT, GETFULLNAME,
    GETPHONE,
    CHECKSMS, PAYMENT,
    GETTOWHERELOCATION,
    GETFROMWHERELOCATION,
    DELETEDRIVER,
    SETTING,
    GETPHONEOFFLINE,
    GETFULLNAMEOFFLINE,
    PHONE,
    REGISTER,
    PASSWORD,
    NONE,
    GETMONEY, SAVEORDERPHONE, GETMONEYPHONE, GETDATEPHONE, DELETEORDERBYID, DELETEORDERLIST, DELETEORDER, DELETEORDERBACKMENU, NODELETEORDER, SAVEOKPHONEORDER, HELPCOMMAND, INSTRUCTIONCOMMAND, CONTACTCOMMAND, CREATIVETEAMCOMMAND, LOCATIONCOMMAND, MAIN

}
